channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - jupyterlab=4.2.*
  - ipywidgets=8.1.*
  - python-dotenv=1.0.*
  - pytorch::faiss-cpu=1.8.*
  - langchain=0.3.*
  - langchain-community=0.3.*
  - langchain-google-genai=2.0.*
  - langgraph=0.2.*